#!/bin/bash
#
# Xi compiler build script
#

# Clean old files
make clean

# Run JFlex on the lexer spec
java -jar lib/jflex-full-1.7.0.jar src/main/java/lexer/xilexer.flex -d src/main/java/lexer/

#Run cup
./lib/cup -parser "XiParser" -destdir ./src/main/java/xi_parser -locations ./src/main/java/xi_parser/xi.cup
./lib/cup -parser "IxiParser" -destdir ./src/main/java/xi_parser -locations ./src/main/java/xi_parser/ixi.cup

# Create the compiler using gradle, create xic binary
if which gradle > /dev/null; then
    # gradle installed by package manager
    gradle --no-daemon customFatJar
else
    # gradle not installed by package manager, try the gradle wrapper supplied
    ./gradlew --no-daemon customFatJar
fi
cat make_jar_executable.sh build/libs/all-in-one-jar-1.0-SNAPSHOT.jar > xic && chmod +x xic

# Link the xic binary in ~/bin
xic_path=$(readlink -f xic)
mkdir -p ~/bin && cd ~/bin
ln -s -f $xic_path xic && cd - > /dev/null
