
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326
//----------------------------------------------------

package xi_parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int UNDERSCORE = 9;
  public static final int CHAR_LIT = 4;
  public static final int LENGTH = 15;
  public static final int LT = 27;
  public static final int INT_LIT = 5;
  public static final int error = 1;
  public static final int MINUS = 17;
  public static final int RETURN = 14;
  public static final int MULT = 20;
  public static final int SEMICOLON = 34;
  public static final int LTEQ = 29;
  public static final int ELSE = 13;
  public static final int ERROR = 42;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int IF = 11;
  public static final int RCURL = 41;
  public static final int HI_MULT = 21;
  public static final int COMMA = 35;
  public static final int MOD = 23;
  public static final int OR = 31;
  public static final int BOOL_LIT = 6;
  public static final int USE = 10;
  public static final int RBRAC = 39;
  public static final int LPAREN = 36;
  public static final int COLON = 33;
  public static final int RPAREN = 37;
  public static final int EQ = 16;
  public static final int GT = 26;
  public static final int BOOL_TYPE = 8;
  public static final int DIV = 22;
  public static final int UMINUS = 32;
  public static final int LBRAC = 38;
  public static final int NOT = 19;
  public static final int STRING_LIT = 3;
  public static final int LCURL = 40;
  public static final int AND = 30;
  public static final int EQEQ = 24;
  public static final int GTEQ = 28;
  public static final int WHILE = 12;
  public static final int NEQ = 25;
  public static final int INT_TYPE = 7;
  public static final int PLUS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING_LIT",
  "CHAR_LIT",
  "INT_LIT",
  "BOOL_LIT",
  "INT_TYPE",
  "BOOL_TYPE",
  "UNDERSCORE",
  "USE",
  "IF",
  "WHILE",
  "ELSE",
  "RETURN",
  "LENGTH",
  "EQ",
  "MINUS",
  "PLUS",
  "NOT",
  "MULT",
  "HI_MULT",
  "DIV",
  "MOD",
  "EQEQ",
  "NEQ",
  "GT",
  "LT",
  "GTEQ",
  "LTEQ",
  "AND",
  "OR",
  "UMINUS",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRAC",
  "RBRAC",
  "LCURL",
  "RCURL",
  "ERROR"
  };
}

